version: '3'
services:
  marketing:
    restart: unless-stopped
    build:
      context: ../ui/marketing
    # Doesn't have to be on the netowkr.
    ports:
      - 8080:8080
  # spa:
  #   ports:
  #     - 8001:8081
  #   networks:
  #     - enterprise
  # db:
  #   # TODO, choose service, mount db volume
  #   networks:
  #     - enterprise
  # server:
  #   # TODO choose good python base, load app, connect DB
  #   networks:
  #     - enterprise
  # TODO: Tools will actually corrospond 1:1 with services here.
  # TODO(cont.): For example, a message bus would be a standalone service.
networks:
  enterprise:
    driver: bridge
