version: '3'
services:
  marketing:
    build:
      context: ../ui/marketing
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=marketing.app.local
    networks:
      - enterprise
  spa:
    build:
      context: ../ui/spa
    networks:
      - enterprise
    ports:
      - 8081:3000
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=dev.app.local
  # db:
  server:
    build:
      context: ../backend
    ports:
      - 8001:80
    networks:
      - enterprise
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=api.app.local
  dns:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    networks:
      - enterprise
  # TODO: Tools will actually corrospond 1:1 with services here.
  # TODO(cont.): For example, a message bus would be a standalone service.
networks:
  enterprise:
    driver: bridge
